managedBy: Helm

targetNamespaces: ""

excludeNamespaces: ""

targetWorkloads: "pod,replicaset,replicationcontroller,statefulset,daemonset,cronjob,job"

nameOverride: ""
fullnameOverride: ""

operator:
  namespace: ""
  replicas: 1

  podLabels: {}

  leaderElectionId: "trivyoperator-lock"

  logDevMode: false

  scanJobTimeout: 5m

  scanJobsConcurrentLimit: 10

  scanJobsRetryDelay: 30s

  vulnerabilityScannerEnabled: true
  scannerReportTTL: "24h"
  configAuditScannerEnabled: true
  rbacAssessmentScannerEnabled: true
  infraAssessmentScannerEnabled: true
  batchDeleteLimit: 10
  vulnerabilityScannerScanOnlyCurrentRevisions: true
  configAuditScannerScanOnlyCurrentRevisions: true
  batchDeleteDelay: 10s
  accessGlobalSecretsAndServiceAccount: true
  builtInTrivyServer: false

  trivyServerHealthCheckCacheExpiration: 10h

  metricsFindingsEnabled: true

  metricsVulnIdEnabled: false

  exposedSecretScannerEnabled: true

  webhookBroadcastURL: ""

  webhookBroadcastTimeout: 30s

  privateRegistryScanSecretsNames: {}
  mergeRbacFindingWithConfigAudit: false

image:
  repository: "ghcr.io/aquasecurity/trivy-operator"
  tag: ""
  pullPolicy: IfNotPresent
  pullSecrets: []

service:
  metricsPort: 80

serviceMonitor:
  enabled: false
  interval: ""
  labels: {}

trivyOperator:
  vulnerabilityReportsPlugin: "Trivy"
  configAuditReportsPlugin: "Trivy"
  scanJobCompressLogs: true
  scanJobTolerations: []
  scanJobNodeSelector: {}

  scanJobAutomountServiceAccountToken: false
  scanJobAnnotations: ""

  scanJobPodTemplateLabels: ""
  scanJobPodTemplatePodSecurityContext: {}

  scanJobPodTemplateContainerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    privileged: false
    readOnlyRootFilesystem: true
  reportResourceLabels: ""

  reportRecordFailedChecksOnly: true

  skipResourceByLabels: ""

  metricsResourceLabelsPrefix: "k8s_label_"

trivy:
  createConfig: true

  repository: ghcr.io/aquasecurity/trivy
  tag: 0.35.0
  mode: Standalone

  additionalVulnerabilityReportFields: ""


  nonSslRegistries: {}

  insecureRegistries: {}
  registry:
    mirror: {}
  severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL

  slow: true
  ignoreUnfixed: false
  skipDirs:

  offlineScan: false

  timeout: "5m0s"

  resources:
    requests:
      cpu: 100m
      memory: 100M
    limits:
      cpu: 500m
      memory: 500M

  serverTokenHeader: "Trivy-Token"


  dbRepository: "ghcr.io/aquasecurity/trivy-db"

  dbRepositoryInsecure: "false"

  useBuiltinRegoPolicies: "true"

  supportedConfigAuditKinds: "Workload,Service,Role,ClusterRole,NetworkPolicy,Ingress,LimitRange,ResourceQuota"

  command: image
  serverUser: ""
  serverPassword: ""
  serverServiceName: "trivy-service"

compliance:
  failEntriesLimit: 10

rbac:
  create: true
serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext:
  privileged: false
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

priorityClassName: ""

automountServiceAccountToken: true
